
spring:
  datasource:
    url: jdbc:mysql://containers-us-west-130.railway.app:8064/railway
    username: root
    password: lTDCtDfbrjZSqB3KqBD2
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  signing-key: 423F4528482B4D6251655368566D597133743677397A24432646294A404E6352
  token-prefix: Bearer
  header: Authorization
  expiration: 3600000  # 1 hour
  refresh-token:
    expiration: 86400000 # 7 days